version: '3.4'

services:
  api-gateway:
    # restart: always
    # privileged: true
    container_name: exchange-api-gateway
    build: app
    # volumes:
    #   - ../../coins/btc/bitcoin.conf:/etc/nginx/bitcoin.conf
    ports:
      - 80:80
      - 443:443
