version: '3.4'

# networks:
#   state:

services:
  api-gateway:
    # restart: always
    # privileged: true
    container_name: exchange-api-gateway
    build: app
    # volumes:
    #   - ../../coins/btc/bitcoin.conf:/etc/nginx/bitcoin.conf
    ports:
      - 80:80
      - 443:443
    env_file:
      - app/env.vars
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off; load_module /etc/nginx/modules/ngx_http_perl_module-debug.so;'"
    # environment:
      # - BINANCE_URL=https://www.google.com
      # - FTX_URL=https://www.dev.to
    # environment:
      # BINANCE_URL: https://www.google.com
      # SERVICE_NAME: authentication
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "100m"

